### ISSUE TITLE
A white stripe appears

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.stepmania.StepMania#1]
![captura de tela de 2018-09-07 09-54-49](https://user-images.githubusercontent.com/26097419/45220305-1571b200-b284-11e8-96d5-fa26852ad35f.png)

**Comment by FakeShemp** [comment]
I get the same.
![screenshot from 2018-09-07 20-11-00](https://user-images.githubusercontent.com/7952047/45235777-45e43b00-b2da-11e8-981d-0dc2c60e066b.png)

**Comment by Kekun** [comment]
Lucky people, for me the game crashes/freezes before the title screen, yet it works perfectly if I build the Flatpak localy.

**Comment by TingPing** [comment]
>  yet it works perfectly if I build the Flatpak localy.

Are you installing it locally too, or using `flatpak-builder --run` or such?

**Comment by Kekun** [comment]
When it worked I ran it with `flatpak-builder --run`. Does it enable some options silently or something? :o

**Comment by TingPing** [comment]
> When it worked I ran it with flatpak-builder --run. Does it enable some options silently or something? :o

Yes it is a useless command, please avoid it and do `--user --install` then `flatpak run ...`

**Comment by barthalion** [comment]
Supposedly fixed by #3
